    <link rel="stylesheet" href="{{ asset('admin_assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/font_awesome_5_free.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/bootstrap-datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/bootstrap-timepicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/bootstrap-tagsinput.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/duotone-dark.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/iziToast.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/fontawesome-iconpicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/bootstrap4-toggle.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/components.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/spacing.css') }}">
    <link rel="stylesheet" href="{{ asset('admin_assets/css/custom.css') }}">